lib/stickertrade_web/router.ex
defmodule StickertradeWeb.Router do
  use StickertradeWeb, :router

  import StickertradeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StickertradeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StickertradeWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/market", MarketViewController, :index
    get "/trades", TradesViewController, :index
  end

  scope "/", StickertradeWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/stickers/add", StickerAddLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", StickertradeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: StickertradeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", StickertradeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", StickertradeWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", StickertradeWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/stickertrade_web/views/layout_view.ex
defmodule StickertradeWeb.LayoutView do
  use StickertradeWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/stickertrade_web/templates/layout/_user_menu.html.heex
<ul class="flex items-center p-2 bg-secondary-400">
<%= if @current_user do %>
  <p class="text-white pl-1 pr-2"><%= @current_user.username %></p>
  <button class="btn-secondary"><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></button>
  <button class="btn-secondary"><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></button>
<% else %>
  <button class="btn-secondary"><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></button>
  <button class="btn-secondary"><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></button>
<% end %>
</ul>

lib/stickertrade_web/templates/layout/app.html.heex
<main>
  <div class="w-1/3 mx-auto text-center">
    <%= if get_flash(@conn, :info) do %>
      <p class="alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <p class="alert-error" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>
  </div>
  <%= @inner_content %>
</main>

lib/stickertrade_web/templates/layout/live.html.heex
<main>
  <p role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/stickertrade_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Sticker Trade" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script defer src="//unpkg.com/alpinejs"></script>
  </head>
  <body class="h-full bg-primary">
    <div class="min-h-full bg-backdrop p-2 border-8 border-primary">
      <header>
        <section>
          <nav class="p-2 flex items-center justify-between h-16">
            <div class="bg-primary-400 p-2">
              <button class="btn-primary"><%= link "Sticker Trade", to: Routes.page_path(@conn, :index) %></button>
              <button class="btn-primary"><%= link "Market", to: Routes.market_view_path(@conn, :index) %></button>
              <button class="btn-primary"><%= link "Trades", to: Routes.trades_view_path(@conn, :index) %></button>
            </div>
            <%= render "_user_menu.html", assigns %>
          </nav>
        </section>
      </header>
      <%= @inner_content %>
    </div>
  </body>
</html>